
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Poppins } from "next/font/google";
import { getAuthSession } from "@/utils/auth";


const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getAuthSession();
  console.log("Session in RootLayout:", session);
  return (
    <html lang="en" className="">
      <body
        className={`${poppins.className}  antialiased`}
      >
        <Navbar />
        {children}
        
      </body>
    </html>
  );
}
